name: build-sonarqube-images

on:

  push:
    branches: [ main ]
    paths:
      - 'tools/sonarqube/**'

  pull_request:
    branches: [ main ]
    paths:
      - 'tools/sonarqube/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}    
        
    - name: Build Sonarqube Image
      run: |
        docker build ./tools/sonarqube -t "inovedados/sonarqube:6.7-openshift"

    - name: docker push
      run: |
        docker push inovedados/sonarqube:6.7-openshift