name: build-php-nginx-images

on:

  push:
    branches: [ main ]
    paths:
      - 'php/nginx/**'

  pull_request:
    branches: [ main ]
    paths:
      - 'php/nginx/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build PHP 7.4 Image
      run: |
        docker build ./php/nginx -t "inovedados/php:7.4-nginx" --build-arg PHP_VERSION=7.4 --build-arg PHP_XDEBUG_VERSION=3.1.5

    - name: Build PHP 8.0 Image
      run: |
        docker build ./php/nginx -t "inovedados/php:8.0-nginx" --build-arg PHP_VERSION=8.0 --build-arg PHP_XDEBUG_VERSION=3.2.2

    - name: Build PHP 8.1 Image
      run: |
        docker build ./php/nginx -t "inovedados/php:8.1-nginx" --build-arg PHP_VERSION=8.1 --build-arg PHP_XDEBUG_VERSION=3.2.2

    - name: Build PHP 8.2 Image
      run: |
        docker build ./php/nginx -t "inovedados/php:8.2-nginx" --build-arg PHP_VERSION=8.2 --build-arg PHP_XDEBUG_VERSION=3.2.2

    - name: docker push
      run: |
        docker push inovedados/php:7.4-nginx
        docker push inovedados/php:8.0-nginx
        docker push inovedados/php:8.1-nginx
        docker push inovedados/php:8.2-nginx