name: build-gitlab-ci-images

on:

  push:
    branches: [ main ]
    paths:
      - 'php/gitlab-ci/**'

  pull_request:
    branches: [ main ]
    paths:
      - 'php/gitlab-ci/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}    
        
    - name: Build Image
      run: |
        docker build ./php/gitlab-ci -t "inovedados/php:7.4-gitlab-ci"

    - name: docker push
      run: |
        docker push inovedados/php:7.4-gitlab-ci