name: build-php-nginx-images

on:

  push:
    branches: [ main ]
    paths:
      - 'php/nginx/**'

  pull_request:
    branches: [ main ]
    paths:
      - 'php/nginx/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build PHP 8.0 Image
      run: |
        docker build ./php/nginx -t "inovedados/php:8.0-nginx-openshift" --build-arg PHP_VERSION=8.0

    - name: Build PHP 8.1 Image
      run: |
        docker build ./php/nginx -t "inovedados/php:8.1-nginx-openshift" --build-arg PHP_VERSION=8.1

    - name: docker push
      run: |
        docker push inovedados/php:8.0-nginx-openshift
        docker push inovedados/php:8.1-nginx-openshift
