name: build-php-nginx-images

on:

  push:
    branches: [ main ]
    paths:
      - 'php/nginx/**'

  pull_request:
    branches: [ main ]
    paths:
      - 'php/nginx/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build PHP 8.0 Image
      run: |
        docker build ./php/nginx -t "inovedados/php:8.0-node-16-nginx" --build-arg PHP_VERSION=8.0 --build-arg PHP_XDEBUG_VERSION=3.2.2 --build-arg NODE_VERSION=16
        docker build ./php/nginx -t "inovedados/php:8.0-node-17-nginx" --build-arg PHP_VERSION=8.0 --build-arg PHP_XDEBUG_VERSION=3.2.2 --build-arg NODE_VERSION=17
        docker build ./php/nginx -t "inovedados/php:8.0-node-18-nginx" --build-arg PHP_VERSION=8.0 --build-arg PHP_XDEBUG_VERSION=3.2.2 --build-arg NODE_VERSION=18
        docker build ./php/nginx -t "inovedados/php:8.0-node-19-nginx" --build-arg PHP_VERSION=8.0 --build-arg PHP_XDEBUG_VERSION=3.2.2 --build-arg NODE_VERSION=19
        docker build ./php/nginx -t "inovedados/php:8.0-node-20-nginx" --build-arg PHP_VERSION=8.0 --build-arg PHP_XDEBUG_VERSION=3.2.2 --build-arg NODE_VERSION=20

    - name: docker push
      run: |
        docker push inovedados/php:8.0-node-16-nginx
        docker push inovedados/php:8.0-node-17-nginx
        docker push inovedados/php:8.0-node-18-nginx
        docker push inovedados/php:8.0-node-19-nginx
        docker push inovedados/php:8.0-node-20-nginx