name: build images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}    
        
    - name: Build PHP 7.4 CLI Image
      run: |
        docker build ./cli -t "inovedados/php:7.4-cli-openshift" --build-arg PHP_VERSION=php74
      

    - name: docker push
      run: |
        docker push inovedados/php:7.4-cli-openshift
