name: build images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}    
        
    - name: Build Images
      run: |
        for i in 7.1 7.2 7.3 7.4 8.0; do docker build . -t "inovedados/php:$i-openshift" --build-arg php=$i; done

    - name: docker push
      run: |
        docker push inovedados/php:7.0-openshift
        docker push inovedados/php:7.1-openshift
        docker push inovedados/php:7.2-openshift
        docker push inovedados/php:7.3-openshift
        docker push inovedados/php:7.4-openshift
        docker push inovedados/php:8.0-openshift
